## Travis build file

language: java
jdk: oraclejdk8
before_install:
    - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
    - mvn install:install-file -DgroupId=edu.drexel -DartifactId=dragontool -Dversion=1.3.3 -Dpackaging=jar -Dfile=libs/dragontool.jar
    - mvn install:install-file -DgroupId=com.github.mpkorstanje -DartifactId=simmetrics -Dversion=4.1.0L -Dpackaging=jar -Dfile=libs/simmetrics.jar
